# Generated by Django 5.0.6 on 2024-07-03 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_alter_profissional_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_cliente', models.CharField(max_length=255, verbose_name='Cliente')),
                ('telefone_cliente', models.CharField(max_length=255, verbose_name='telefone')),
                ('email_cliente', models.EmailField(max_length=100, verbose_name='Email')),
                ('profissional_selecionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profissional')),
                ('servico_selecionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servico')),
            ],
        ),
    ]
