# Generated by Django 5.0.6 on 2024-07-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_agendamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('horario', models.TimeField()),
            ],
        ),
    ]
