# Generated by Django 5.0.6 on 2024-07-04 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_horarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Horarios',
            new_name='Horario',
        ),
    ]
