# Generated by Django 5.0.6 on 2024-07-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_horarios_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='horario',
            field=models.CharField(max_length=10),
        ),
    ]
