# Generated by Django 5.0.6 on 2024-07-04 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_horario_horario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agendamento',
        ),
    ]
