# Generated by Django 5.0.6 on 2024-07-04 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_agendamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='horario_selecionado',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='profissional_selecionado',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='servico_selecionado',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
        migrations.DeleteModel(
            name='Profissional',
        ),
        migrations.DeleteModel(
            name='Agendamento',
        ),
        migrations.DeleteModel(
            name='Servico',
        ),
    ]
