# Generated by Django 5.0.6 on 2024-07-04 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_remove_agendamento_horario_selecionado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('horario', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('servico', models.CharField(max_length=255, verbose_name='Serviço')),
                ('valor', models.CharField(max_length=255, verbose_name='Valor')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Nome de Usuário')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('endereco', models.CharField(max_length=1000, verbose_name='Endereço')),
                ('bairro', models.CharField(max_length=255, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=255, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=255, verbose_name='UF')),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(verbose_name='Data')),
                ('nome_cliente', models.CharField(max_length=255, verbose_name='Cliente')),
                ('telefone_cliente', models.CharField(max_length=255, verbose_name='telefone')),
                ('email_cliente', models.EmailField(max_length=100, verbose_name='Email')),
                ('horario_selecionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.horario')),
                ('profissional_selecionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profissional')),
                ('servico_selecionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servico')),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.horario')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profissional')),
            ],
            options={
                'unique_together': {('profissional', 'horario', 'data')},
            },
        ),
    ]
