# Generated by Django 5.0.6 on 2024-07-05 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disponibilidade',
        ),
    ]
