# Generated by Django 5.0.6 on 2024-07-09 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_disponibilidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='email_cliente',
        ),
    ]
