# Generated by Django 5.0.6 on 2024-07-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_horario_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='horario',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
