# Generated by Django 5.0.6 on 2024-07-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_horario_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='info',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
