# Generated by Django 5.0.6 on 2024-07-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_agendamento_info_agendamento_finalizado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
