# Generated by Django 5.0.6 on 2024-07-16 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
