# Generated by Django 5.0.6 on 2024-07-16 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_agendamento_horario_selecionado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='horario_selecionado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.horario'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='profissional_selecionado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profissional'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='servico_selecionado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servico'),
        ),
    ]
