# Generated by Django 5.0.6 on 2024-07-16 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_agendamento_horario_selecionado_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agendamento',
        ),
    ]
