# Generated by Django 5.0.6 on 2024-07-17 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_agendamento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agendamento',
        ),
    ]
