# Generated by Django 5.0.6 on 2024-07-18 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_agendamento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
