# Generated by Django 5.0.6 on 2024-07-18 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_delete_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Horario',
        ),
        migrations.DeleteModel(
            name='Profissional',
        ),
        migrations.DeleteModel(
            name='Servico',
        ),
    ]
