# Generated by Django 5.0.6 on 2024-07-30 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_delete_horario_delete_profissional_delete_servico'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agendamento',
        ),
    ]
