# Generated by Django 5.0.6 on 2024-07-18 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_barbearia', '0002_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('horario', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('servico', models.CharField(max_length=255, verbose_name='Serviço')),
                ('valor', models.CharField(max_length=255, verbose_name='Valor')),
            ],
        ),
    ]
