# Generated by Django 5.0.6 on 2024-07-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_barbearia', '0003_horario_profissional_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='disponivel',
            field=models.BooleanField(default=False, verbose_name='Disponível'),
        ),
    ]
