# Generated by Django 5.0.6 on 2024-07-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_barbearia', '0004_profissional_disponivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='disponivel',
            field=models.BooleanField(default=True, verbose_name='Disponível'),
        ),
    ]
